FROM node:18-buster AS build

WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY ./ ./
RUN npm i
CMD ["npm", "run", "build"]

FROM nginx:stable AS server

COPY --from build /app/out /usr/share/nginx/html