version: '3.8'

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      # add database credentials
      - DB_USER=[db user]
      - DB_HOST=[db host]
      - DB_NAME=[db name]
      - DB_PASSWORD=[db password]
      - DB_PORT=[db port most likely 5432]
      # add oauth environment var
      - ACCESS_TOKEN_SECRET=SUPER_SECRET_ACCESS_KEY
      - REFRESH_TOKEN_SECRET=SUPER_SECRET_REFRESH_KEY

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_SERVER_URL=http://localhost:3001
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
